# Generated by Django 3.1.4 on 2021-11-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_malady_paitent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Malady',
        ),
    ]
