# Generated by Django 3.1.4 on 2021-11-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_malady_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='malady',
            name='mobile',
            field=models.IntegerField(default=None),
        ),
    ]
