# Generated by Django 3.1.4 on 2021-11-17 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discover', '0006_auto_20211117_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malady',
            name='paitent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
