# Generated by Django 3.1.4 on 2021-11-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0008_auto_20211119_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malady',
            name='paitent',
        ),
    ]
